# Generated by Django 5.0.6 on 2024-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentassignment_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='student_profile_imgs/'),
        ),
    ]
