# Generated by Django 5.0.6 on 2024-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notiy_text', models.TextField()),
                ('notify_for', models.CharField(max_length=100)),
                ('notify_created_time', models.DateTimeField(auto_now_add=True)),
                ('notify_read_status', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name_plural': '10.Notification',
            },
        ),
    ]
