# Generated by Django 5.0.6 on 2024-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_notification_student_notification_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
